### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by mikulatomas**
Logo is created and added.

Font used in the logo is called `Roboto Slab`, it's license should be fine (https://fonts.google.com/specimen/Roboto+Slab#license). Rest of the graphics is completely made by me from scratch. I can create more variations if needed.

Logo in the docs is in `svg`, `png` is used in README but should be large enough to look good on retina displays.

Known issues:
Logo in `README.rst` is duplicated in root folder and `docs/`. Reason is that sphinx requires it because `README.rst` is included in index, but Github uses it as main `README.rst` and relative paths to `docs/` are broken. Fix it if you know how :)

### CODE REVIEW

**Comment by xflr6** [comment]
Thanks Tomáš.

> Logo in `README.rst` is duplicated in root folder and `docs/`. Reason is that sphinx requires it because
> `README.rst` is included in index, but Github uses it as main `README.rst` and relative paths to
> `docs/` are broken. 

How about using the `.png` file directly from the repo in `README.rst` as we do for the other image [here](https://github.com/xflr6/graphviz/blame/master/README.rst#L105)?

**Comment by mikulatomas** [comment]
> How about using the `.png` file directly from the repo in `README.rst` as we do for the other image [here](https://github.com/xflr6/graphviz/blame/master/README.rst#L105)?

That would be best, but it has to be pulled into master first right? I will prepare the link (will be broken before pull request done) and than you can merge it.

**Comment by xflr6** [comment]
Yep (it's also a workaround but maybe a bit more maintainable). SG.

**Comment by mikulatomas** [comment]
Squashed and ready for pull :)

**Comment by xflr6** [comment]
Thanks!

**Pull request merged**
