### PR TITLE
Add new function in lattice.py and visualize.py

### PR DESCRIPTION
**Pull request by NNKS0505**
Hello, I'm a student at Kyushu University.
I add new function in lattice.py and visualize.py. 
In attachment, I explain detail about this, so I would like you to confirm this attachment.

[New function added in Concepts package.pdf](https://github.com/xflr6/concepts/files/5371612/New.function.added.in.Concepts.package.pdf)

### CODE REVIEW

**Comment by xflr6** [comment]
Hi there. Thanks for the proposal.

When it comes to changing the style/formatting of the visualization, a lot is already supported if you use the [API of the returned object](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.Graph). This is [mentioned in the docs](https://concepts.readthedocs.io/en/stable/manual.html#visualization), but without giving some examples. I have just added [Visualization.ipynb](https://nbviewer.jupyter.org/github/xflr6/concepts/blob/master/examples/Visualization.ipynb) replicating most of the graphs from the attachment you provided (hope that helps). I am considering to integrate this into the docs, WDYT?

IIUC the only thing left is emphazising/highlighting a node, which I think might be a nice addition (maybe `highlight` would be a better argument name). It might make sense to do something more general such as adding a callable `make_node_format` argument to [`.graphviz()`](https://concepts.readthedocs.io/en/stable/api.html#concepts.lattices.Lattice.graphviz). It could take a `Concept` instance as argument returning a dict with formatting attributes that will be used for the node in the visualization. That function could then use any attributes on that object to control the format, e.g. to implement highlighting similar to proposed:

```python
assert isinstance(lattice, Lattice)
highlight = lattice[...]   # a Concept instance

def make_node_format(concept):
    if concept is highlight:
        return {'color': 'red'}
    if highlight in concept.upper_neighbors or highlight in concept.lower_neighbors:
        return {'color': 'blue'}
    return {}

lattice.graphviz(make_node_format=make_node_format)
```

Tell me if you would like to work on this.

From a quick look, I would say that the code here probably still needs a lot of work (to follow Python best practises and idioms, avoid duplication, fix code formatting, etc.). If you plan to break backwards compatibility (see e.g. [failing tests](https://travis-ci.org/github/xflr6/concepts/builds/735397804)) please document this (in general, I would prefer to do so only with good reasons).

**Comment by NNKS0505** [comment]
Thank you for confirming my attachment and adding Visualization.ipynb. 
I confirmed this, and I also thought that a lot is already supported. 
Therefore, I only would like to work on emphazising/highlighting a node.

My code is not good, so your proposal(adding a callable make_node_format argument to .graphviz()) is better.
Which do you suppose that I will recode or you will recode(adding a callable make_node_format argument to .graphviz())?
If you suppose that I will record, would you teach me more specific about recoding.

**Comment by xflr6** [comment]
Thanks. I have added the content of  [Visualization.ipynb](https://nbviewer.jupyter.org/github/xflr6/concepts/blob/master/examples/Visualization.ipynb) to [the docs](https://concepts.readthedocs.io/en/latest/manual.html#customization) in 6fe7e05c8877aed946ae8b2f90e97be34377c16b.

SG, if you want to give it a try to add the `make_node_format` argument (adding commits here or force-pushing a new commit to replace the current ones). Maybe `make_node_attrs` would be an even better name. I suspect this change will be much smaller than what we currently have.

I am happy to review any upcoming changes here (but keep in mind that my resources for this are limited). If you prefer, I can also take it from here, or at any upcoming change (provided it is clean enough, e.g. not breaking tests).

**Comment by NNKS0505** [comment]
Thanks.
After the conversation with my professor, I will decide whether I try to add the make_format_node(make_node_attrs) or not.
If i try to add this, I will force-pushing a new commit to replace the current ones.

Thank you for reviewing my redundant code, and if my poor English make you uncomfortable, I apologize from the bottom of my heart.

**Comment by xflr6** [comment]
Thanks and no worries :)

**Pull request closed without merging**
